version: '3'

services:
  php:
    container_name: php-store
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    restart: unless-stopped
    tty: true
    volumes:
      - ./store:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
    - store-network

  nginx:
    container_name: nginx-store
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    restart: unless-stopped
    tty: true
    ports:
      - '8080:80'
      - '443:443'
    volumes:
      - ./store:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - store-network

  mysql:
    container_name: mysql-store
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    tty: true
    volumes:
      - setup-data:/var/lib/mysql/
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - store-network
    ports:
      - '3307:3306'
    environment:
      MYSQL_DATABASE: store
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: password
  
  phpmyadmin:
    container_name: phpmyadmin-store
    image: phpmyadmin:5.2
    restart: always
    ports:
      - '8888:80'
    networks:
      - store-network
    environment:
      PMA_HOST: mysql-store
    depends_on:
      - mysql
  
  redis:
    container_name: redis-store
    build:
      context: ./docker/redis
      dockerfile: Dockerfile
    ports:
      - '6379:6379'

networks:
  store-network:
    driver: bridge

volumes:
  setup-data:
    driver: local